USE [master]
GO

/******* Object:  Database [UzzoBinance]    Script Date: 19/01/2021 12:48:22 ******/
CREATE DATABASE [UzzoBinance]
 
GO

ALTER DATABASE [UzzoBinance] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UzzoBinance].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [UzzoBinance] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [UzzoBinance] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [UzzoBinance] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [UzzoBinance] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [UzzoBinance] SET ARITHABORT OFF 
GO

ALTER DATABASE [UzzoBinance] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [UzzoBinance] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [UzzoBinance] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [UzzoBinance] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [UzzoBinance] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [UzzoBinance] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [UzzoBinance] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [UzzoBinance] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [UzzoBinance] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [UzzoBinance] SET  DISABLE_BROKER 
GO

ALTER DATABASE [UzzoBinance] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [UzzoBinance] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [UzzoBinance] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [UzzoBinance] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [UzzoBinance] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [UzzoBinance] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [UzzoBinance] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [UzzoBinance] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [UzzoBinance] SET  MULTI_USER 
GO

ALTER DATABASE [UzzoBinance] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [UzzoBinance] SET DB_CHAINING OFF 
GO

ALTER DATABASE [UzzoBinance] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [UzzoBinance] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [UzzoBinance] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [UzzoBinance] SET QUERY_STORE = OFF
GO

USE [UzzoBinance]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [UzzoBinance] SET  READ_WRITE 
GO


